export type DirectFacilityDto = {
  product: "DIRECT";
  protocolVersion: "interline-direct-v2";
  chainId: number;
  facility: `0x${string}`;
  lender: `0x${string}`;
  borrower: `0x${string}`;
  vault: `0x${string}`;
  asset: { address: `0x${string}`; symbol: string; decimals: number };
  termsHash: `0x${string}`;
  lenderAccepted: boolean;
  borrowerAccepted: boolean;
  declined: boolean;
  cancelled: boolean;
  ended: boolean;
  acceptanceDeadline: string;
  activatedAt: string | null;
  borrowExpiry: string | null;
  repaymentDueAt: string | null;
  creditLimitRaw: string;
  availableCashRaw: string;
  principalRaw: string;
  debtRaw: string;
  accruedInterestRaw: string;
  fixedAprRay: string;
  recallDeadline: string | null;
  borrowingPaused: boolean;
  collateralization: "OVERCOLLATERALIZED_80";
  healthFactorWad: null;
  priceLiquidatable: false;
};
