/**
 * Generate `packages/protocol` ABI + deployment bindings from Foundry `out/`.
 * Do not hand-sync ABI copies.
 *
 *   C:/Users/ACER/.foundry/bin/forge.exe build
 *   node --experimental-strip-types tools/export-abis.ts
 */
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "out");
const DEST = join(ROOT, "packages", "protocol", "src");

/** Contracts whose ABIs the app, keeper, and SDK consume. Libraries have no ABI. */
const CONTRACTS = [
  "LendingMarket",
  "MarketFactory",
  "MarketLens",
  "BorrowerVaultV2",
  "BorrowerVaultFactory",
  "MarketRecoveryEscrow",
  "ChainlinkPairOracle",
  "ERC4626VenueAdapter",
  "TestAsset",
  "TestnetFaucet",
  "MockPriceFeed",
  "MockSequencerFeed",
  "MockERC4626Venue",
  "MockSwapRouter",
] as const;

type Artifact = { abi: unknown[]; bytecode?: { object?: string } };

function findArtifact(name: string): Artifact {
  const direct = join(OUT, `${name}.sol`, `${name}.json`);
  if (existsSync(direct)) {
    return JSON.parse(readFileSync(direct, "utf8")) as Artifact;
  }
  if (!existsSync(OUT)) {
    throw new Error(`Foundry out/ is missing. Run forge build first.`);
  }
  for (const dir of readdirSync(OUT, { withFileTypes: true })) {
    if (!dir.isDirectory()) continue;
    const candidate = join(OUT, dir.name, `${name}.json`);
    if (existsSync(candidate)) {
      return JSON.parse(readFileSync(candidate, "utf8")) as Artifact;
    }
  }
  throw new Error(`No Foundry artifact for ${name} under out/.`);
}

function tsLiteral(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

function writeAbis(): string[] {
  const missing: string[] = [];
  const lines: string[] = [
    "/** AUTO-GENERATED by tools/export-abis.ts from Foundry out/. Do not hand-sync. */",
    "export const abis = {",
  ];
  for (const name of CONTRACTS) {
    try {
      const artifact = findArtifact(name);
      if (!Array.isArray(artifact.abi)) {
        throw new Error(`${name} artifact has no abi array`);
      }
      lines.push(`  ${name}: ${tsLiteral(artifact.abi)} as const,`);
    } catch (err) {
      missing.push(name);
      console.error(err instanceof Error ? err.message : err);
    }
  }
  lines.push("} as const;");
  lines.push("");
  lines.push("export type ProtocolAbis = typeof abis;");
  lines.push("export type ProtocolContractName = keyof ProtocolAbis;");
  lines.push("");
  writeFileSync(join(DEST, "abis.ts"), lines.join("\n"), "utf8");
  return missing;
}

function writeIndex(): void {
  writeFileSync(
    join(DEST, "index.ts"),
    [
      "export { abis, type ProtocolAbis, type ProtocolContractName } from \"./abis.ts\";",
      "export {",
      "  loadV2Manifest,",
      "  manifestPath,",
      "  type DeliveryMode,",
      "  type V2Manifest,",
      "  type V2Market,",
      "} from \"./deployments.ts\";",
      "",
    ].join("\n"),
    "utf8",
  );
}

function main(): void {
  mkdirSync(DEST, { recursive: true });
  const missing = writeAbis();
  writeIndex();
  if (missing.length > 0) {
    console.error(`export-abis: missing artifacts: ${missing.join(", ")}`);
    process.exit(1);
  }
  console.log(`Wrote ${CONTRACTS.length} ABIs to packages/protocol/src/abis.ts`);
}

main();
