export const lendingMarketAbi = [
  {
    type: "function",
    name: "supply",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "minSharesOut", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "withdraw",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "maxSharesBurn", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "redeem",
    stateMutability: "nonpayable",
    inputs: [
      { name: "shares", type: "uint256" },
      { name: "minAssetsOut", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addCollateral",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "removeCollateral",
    stateMutability: "nonpayable",
    inputs: [{ name: "amount", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "borrow",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "maxDebtShares", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "repay",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "maxAssets", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "repayAll",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "maxAssets", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "liquidate",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "exactDebtShares", type: "uint256" },
      { name: "exactCollateral", type: "uint256" },
      { name: "maxLoanAssetsIn", type: "uint256" },
      { name: "minCollateralOut", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "hashCapProposal",
    stateMutability: "view",
    inputs: [
      { name: "owner", type: "address" },
      { name: "newCap", type: "uint256" },
      { name: "nonce", type: "uint256" },
      { name: "expiry", type: "uint256" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "proposeCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "digest", type: "bytes32" },
      { name: "nonce", type: "uint256" },
      { name: "expiry", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "approveCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "digest", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "cancelCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "digest", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "executeCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "owner", type: "address" },
      { name: "newCap", type: "uint256" },
      { name: "nonce", type: "uint256" },
      { name: "expiry", type: "uint256" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "capNonce",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "pendingCapDigest",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "bytes32" }],
  },
  { type: "function", name: "accountedCash", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "totalSupplyShares", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "totalDebtShares", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "indexNow", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "supplySharesOf",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "debtSharesOf",
    stateMutability: "view",
    inputs: [{ name: "owner", type: "address" }],
    outputs: [{ type: "uint256" }],
  },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "InvalidConfig", inputs: [] },
  { type: "error", name: "SameAsset", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "Frozen", inputs: [] },
  { type: "error", name: "TerminalMarket", inputs: [] },
  { type: "error", name: "OracleInvalid", inputs: [] },
  { type: "error", name: "SupplyCapExceeded", inputs: [] },
  { type: "error", name: "BorrowCapExceeded", inputs: [] },
  { type: "error", name: "PositionCapExceeded", inputs: [] },
  { type: "error", name: "InsufficientCash", inputs: [] },
  { type: "error", name: "InsufficientShares", inputs: [] },
  { type: "error", name: "InsufficientCollateral", inputs: [] },
  { type: "error", name: "Slippage", inputs: [] },
  { type: "error", name: "MinAmount", inputs: [] },
  { type: "error", name: "DustDebt", inputs: [] },
  { type: "error", name: "LastShareWithDebt", inputs: [] },
  { type: "error", name: "Healthy", inputs: [] },
  { type: "error", name: "Defaulted", inputs: [] },
  { type: "error", name: "NotCurator", inputs: [] },
  { type: "error", name: "NotGuardian", inputs: [] },
  { type: "error", name: "NotRestricted", inputs: [] },
  { type: "error", name: "RecallInactive", inputs: [] },
  { type: "error", name: "RecallPending", inputs: [] },
  { type: "error", name: "AlreadyRecalled", inputs: [] },
  { type: "error", name: "FeeOnTransfer", inputs: [] },
  { type: "error", name: "NotPending", inputs: [] },
  { type: "error", name: "CapNotProposed", inputs: [] },
  { type: "error", name: "CapNotApproved", inputs: [] },
  { type: "error", name: "CapBelowDebt", inputs: [] },
  { type: "error", name: "Expired", inputs: [] },
  { type: "error", name: "WalletMode", inputs: [] },
  { type: "error", name: "NotEscrow", inputs: [] },
  { type: "error", name: "ExcessRecovery", inputs: [] },
] as const;
