export const DIRECT_APR_RAY = 5n * 10n ** 25n;

const termsTuple = {
  name: "terms",
  type: "tuple",
  components: [
    { name: "lender", type: "address" },
    { name: "borrower", type: "address" },
    { name: "loanToken", type: "address" },
    { name: "creditLimit", type: "uint256" },
    { name: "aprRay", type: "uint256" },
    { name: "acceptanceLifetime", type: "uint32" },
    { name: "borrowPeriod", type: "uint32" },
    { name: "recallWindow", type: "uint32" },
    { name: "venue", type: "address" },
    { name: "swapRouter", type: "address" },
    { name: "otherToken", type: "address" },
  ],
} as const;

export const directFactoryAbi = [
  {
    type: "function",
    name: "createFacility",
    stateMutability: "nonpayable",
    inputs: [termsTuple],
    outputs: [{ name: "facility", type: "address" }],
  },
  { type: "function", name: "loanToken", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "venue", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "swapRouter", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "otherToken", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "facilityCount", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  {
    type: "function",
    name: "facilityAt",
    stateMutability: "view",
    inputs: [{ name: "index", type: "uint256" }],
    outputs: [{ type: "address" }],
  },
  {
    type: "event",
    name: "FacilityCreated",
    inputs: [
      { name: "facility", type: "address", indexed: true },
      { name: "lender", type: "address", indexed: true },
      { name: "borrower", type: "address", indexed: true },
      { name: "vault", type: "address", indexed: false },
      { name: "termsHash", type: "bytes32", indexed: false },
      { name: "creator", type: "address", indexed: false },
    ],
  },
] as const;

export const directFacilityAbi = [
  { type: "function", name: "acceptTerms", stateMutability: "nonpayable", inputs: [{ name: "hash", type: "bytes32" }], outputs: [] },
  { type: "function", name: "decline", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "cancelPending", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "fund", stateMutability: "nonpayable", inputs: [{ name: "assets", type: "uint256" }], outputs: [] },
  { type: "function", name: "withdrawCash", stateMutability: "nonpayable", inputs: [{ name: "assets", type: "uint256" }], outputs: [] },
  { type: "function", name: "addCollateral", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  { type: "function", name: "removeCollateral", stateMutability: "nonpayable", inputs: [{ name: "amount", type: "uint256" }], outputs: [] },
  {
    type: "function",
    name: "borrow",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "maxDebtAfter", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "function", name: "repayAssets", stateMutability: "nonpayable", inputs: [{ name: "maxAssets", type: "uint256" }], outputs: [] },
  { type: "function", name: "repayAll", stateMutability: "nonpayable", inputs: [{ name: "maxAssets", type: "uint256" }], outputs: [] },
  { type: "function", name: "repayFromVault", stateMutability: "nonpayable", inputs: [{ name: "maxAssets", type: "uint256" }], outputs: [] },
  { type: "function", name: "pauseNewBorrowing", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "resumeNewBorrowing", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "requestRepayment", stateMutability: "nonpayable", inputs: [{ name: "reasonCode", type: "uint8" }], outputs: [] },
  { type: "function", name: "clearRecall", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "settleDefault", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "publicRecoveryDeadline", stateMutability: "view", inputs: [], outputs: [{ type: "uint64" }] },
  {
    type: "function",
    name: "previewSettlement",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "collateralToLender", type: "uint256" },
      { name: "residualToBorrower", type: "uint256" },
      { name: "debtCredit", type: "uint256" },
    ],
  },
  {
    type: "function",
    name: "recoverVenue",
    stateMutability: "nonpayable",
    inputs: [
      { name: "assets", type: "uint256" },
      { name: "maxShares", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "recoverSwap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "amountIn", type: "uint256" },
      { name: "minOut", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "function", name: "endAgreement", stateMutability: "nonpayable", inputs: [], outputs: [] },
  { type: "function", name: "recallReasonHash", stateMutability: "view", inputs: [], outputs: [{ type: "bytes32" }] },
  { type: "function", name: "otherToken", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  {
    type: "function",
    name: "hashCapProposal",
    stateMutability: "view",
    inputs: [
      { name: "newCap", type: "uint256" },
      { name: "nonce", type: "uint256" },
      { name: "validUntil", type: "uint256" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [{ type: "bytes32" }],
  },
  {
    type: "function",
    name: "proposeCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "digest", type: "bytes32" },
      { name: "nonce", type: "uint256" },
      { name: "validUntil", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "function", name: "approveCap", stateMutability: "nonpayable", inputs: [{ name: "digest", type: "bytes32" }], outputs: [] },
  { type: "function", name: "cancelCap", stateMutability: "nonpayable", inputs: [{ name: "digest", type: "bytes32" }], outputs: [] },
  {
    type: "function",
    name: "executeCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "newCap", type: "uint256" },
      { name: "nonce", type: "uint256" },
      { name: "validUntil", type: "uint256" },
      { name: "salt", type: "bytes32" },
    ],
    outputs: [],
  },
  { type: "function", name: "termsHash", stateMutability: "view", inputs: [], outputs: [{ type: "bytes32" }] },
  { type: "function", name: "lender", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "borrower", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "vault", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "loanToken", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "creditLimit", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "accountedCash", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "collateralPosted", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "MAX_LTV_BPS", stateMutability: "view", inputs: [], outputs: [{ type: "uint16" }] },
  { type: "function", name: "currentDebt", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "principalOutstanding", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "availableToBorrow", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "aprRay", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "lenderAccepted", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "borrowerAccepted", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "declined", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "cancelled", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "ended", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "borrowingPaused", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "recallActive", stateMutability: "view", inputs: [], outputs: [{ type: "bool" }] },
  { type: "function", name: "recallDeadline", stateMutability: "view", inputs: [], outputs: [{ type: "uint64" }] },
  { type: "function", name: "acceptanceDeadline", stateMutability: "view", inputs: [], outputs: [{ type: "uint64" }] },
  { type: "function", name: "activatedAt", stateMutability: "view", inputs: [], outputs: [{ type: "uint64" }] },
  { type: "function", name: "borrowExpiry", stateMutability: "view", inputs: [], outputs: [{ type: "uint64" }] },
  { type: "function", name: "repaymentDueAt", stateMutability: "view", inputs: [], outputs: [{ type: "uint64" }] },
  { type: "function", name: "capNonce", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "pendingCapDigest", stateMutability: "view", inputs: [], outputs: [{ type: "bytes32" }] },
  { type: "function", name: "pendingCapNonce", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "pendingCapValidUntil", stateMutability: "view", inputs: [], outputs: [{ type: "uint64" }] },
  { type: "function", name: "debtShares", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "indexNow", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "SameParty", inputs: [] },
  { type: "error", name: "WrongParty", inputs: [] },
  { type: "error", name: "InvalidTerms", inputs: [] },
  { type: "error", name: "NotPending", inputs: [] },
  { type: "error", name: "AlreadyDecided", inputs: [] },
  { type: "error", name: "RequestExpired", inputs: [] },
  { type: "error", name: "NotBothAccepted", inputs: [] },
  { type: "error", name: "NotActive", inputs: [] },
  { type: "error", name: "NoLenderCash", inputs: [] },
  { type: "error", name: "LimitExceeded", inputs: [] },
  { type: "error", name: "BorrowingExpired", inputs: [] },
  { type: "error", name: "LenderPaused", inputs: [] },
  { type: "error", name: "ActiveRecall", inputs: [] },
  { type: "error", name: "RecallInactive", inputs: [] },
  { type: "error", name: "AlreadyRecalled", inputs: [] },
  { type: "error", name: "OutstandingDebt", inputs: [] },
  { type: "error", name: "OutstandingCash", inputs: [] },
  { type: "error", name: "OutstandingExposure", inputs: [] },
  { type: "error", name: "Ended", inputs: [] },
  { type: "error", name: "ZeroAmount", inputs: [] },
  { type: "error", name: "Slippage", inputs: [] },
  { type: "error", name: "FeeOnTransfer", inputs: [] },
  { type: "error", name: "CapNotProposed", inputs: [] },
  { type: "error", name: "CapNotApproved", inputs: [] },
  { type: "error", name: "CapBelowDebt", inputs: [] },
  { type: "error", name: "Expired", inputs: [] },
  { type: "error", name: "InsufficientCollateral", inputs: [] },
  { type: "error", name: "OracleInvalid", inputs: [] },
  { type: "error", name: "SettlementClosed", inputs: [] },
] as const;

export const borrowerVaultAbi = [
  { type: "function", name: "enterVenue", stateMutability: "nonpayable", inputs: [{ name: "assets", type: "uint256" }, { name: "minShares", type: "uint256" }], outputs: [] },
  { type: "function", name: "exitVenue", stateMutability: "nonpayable", inputs: [{ name: "assets", type: "uint256" }, { name: "maxShares", type: "uint256" }], outputs: [] },
  { type: "function", name: "redeemVenue", stateMutability: "nonpayable", inputs: [{ name: "shares", type: "uint256" }, { name: "minAssets", type: "uint256" }], outputs: [] },
  {
    type: "function",
    name: "swap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "tokenIn", type: "address" },
      { name: "tokenOut", type: "address" },
      { name: "amountIn", type: "uint256" },
      { name: "minOut", type: "uint256" },
      { name: "deadline", type: "uint256" },
    ],
    outputs: [{ type: "uint256" }],
  },
  {
    type: "function",
    name: "releaseSurplus",
    stateMutability: "nonpayable",
    inputs: [
      { name: "token", type: "address" },
      { name: "amount", type: "uint256" },
    ],
    outputs: [],
  },
  { type: "function", name: "idleLoan", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "venueShares", stateMutability: "view", inputs: [], outputs: [{ type: "uint256" }] },
  { type: "function", name: "otherToken", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "loanToken", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
  { type: "function", name: "owner", stateMutability: "view", inputs: [], outputs: [{ type: "address" }] },
] as const;
